feat: support Cargo.toml version bumping

diff --git a/bin/bump b/bin/bump
--- a/bin/bump
+++ b/bin/bump
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 version="$1"
 
+check_diff() {
+  if [ $(git diff "$1" | wc -l) -ne 0 ]; then
+    echo "Refusing to proceed - uncommitted changes to "$1" found"
+    exit 1
+  fi
+}
+
 if [ -z "$version" ]; then
   echo "usage: bump <version>"
   exit 2
@@ -8,24 +15,32 @@ fi
 
 if [ -f package.json ]; then
   echo "package.json found"
-  if [ $(git diff package.json | wc -l) -ne 0 ]; then
-    echo "Refusing to proceed - uncommitted changes to package.json found"
-    exit 1
-  fi
+  check_diff package.json
 
   if [ "$(json version < package.json)" != "$version" ]; then
     echo "Bumping package.json version"
     json -e "this.version=\"$1\"" < package.json > package.tmp.json
     mv package.tmp.json package.json
-    git commit package.json -m "Bump to version $1"
     echo "Here's what I did to your package.json:"
-    git --no-pager show
+    git add package.json
+    git --no-pager diff --cached package.json
   fi
 fi
 
-git tag -s -a -m "Version $1" "v$1"
+if [ -f Cargo.toml ]; then
+  echo "Cargo.toml found"
+  check_diff Cargo.toml
+  sed -Ee "s/version(\s*)=(\s*)\"(.*)\"/version\1=\2\"$version\"/" -i Cargo.toml
+  git add Cargo.toml
+  echo "Here's what I did to your Cargo.toml:"
+  git --no-pager diff --cached Cargo.toml
+fi
 
-if [ $? -ne 0 ] && [ -f package.json ]; then
-  echo "Tagging failed, reverting changes I made to package.json"
+git commit -m "Bump to version $1"
+
+git tag -a -m "Version $1" "v$1"
+
+if [ $? -ne 0 ]; then
+  echo "Tagging failed, reverting changes I made"
   git reset --hard HEAD^
 fi
